name: Common Repo
on:
  workflow_dispatch:
  repository_dispatch:
    types: [test_dispatch]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v2

      - name: Set Client Payload
        id: set-payload
        run: echo "::set-output name=payload::{\"run_id\":\"${{ github.run_id }}\",\"workflow_number\":\"${{ github.run_number }}\"}"
       
      - name: Set Payload Environment Variable
        run: |
          echo 'export CLIENT_PAYLOAD="your_client_payload_data"' >> $GITHUB_ENV

      - name: Trigger Microservice Main Build
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            "https://api.github.com/repos/yourorg/yourrepo/actions/workflows/microservice-main-build.yml/dispatches" \
            -d '{"ref": "main", "inputs": {"client_payload": "${CLIENT_PAYLOAD}"}}'
