name: Common Repo
on:
  workflow_dispatch:
  repository_dispatch:
    types: [test_dispatch]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v2

      - name: Set Client Payload
        id: set-payload
        run: echo "::set-output name=payload::{\"run_id\":\"${{ github.run_id }}\",\"workflow_number\":\"${{ github.run_number }}\"}"
       
       # Set the client payload data with run_id and workflow_number
      #- name: Set Client Payload
      #  id: set-payload
      #  run: echo "::set-output name=payload::{\"run_id\":\"${{ github.run_id }}\",\"workflow_number\":\"${{ github.run_number }}\"}"
