name: Common Repo
on:
  workflow_dispatch:
  repository_dispatch:
    types: [test_dispatch]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v2
        if: github.event.client_payload.ref != ''
        with:
          ref: ${{ github.event.client_payload.ref }}

      - run: echo ${{ github.event.client_payload.sha }}
