name: Common Repo
on:
  workflow_dispatch:
  repository_dispatch:
    types: [test_dispatch]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v2
      - name: Echo GitHub Payload
        run: echo "Source Workflow Run ID:${{ github.event.client_payload.source_workflow_run_id }}"
