name: Test Zoom Chat API

on:
  workflow_dispatch:
jobs:
  test-zoom-chat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Obtain Access Token
        id: get-token
        run: |
          AUTH=$(echo -n "IxKWwRr1ScyLLHeBDujbQ:gCA1n61W9c6laxrmu1ZcWUgGVJdpvtcL" | base64)
          RESPONSE=$(curl --request POST \
            --url https://zoom.us/oauth/token \
            --header "Authorization: Basic $AUTH" \
            --header 'Content-Type: application/x-www-form-urlencoded' \
            --data "grant_type=client_credentials")
          echo "$RESPONSE"
          ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Send Chat Message
        run: |
          curl --request POST \
            --url https://api.zoom.us/v2/chat/users/me/messages \
            --header "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
            --header 'Content-Type: application/json' \
            --data '{
              {
                  "at_items": [
                    {
                      "at_contact": "vcpsuthakar@gmail.com",
                      "at_type": 2,
                      "end_position": 8,
                      "start_position": 0
                    }
                  ],
                  "rich_text": [
                    {
                      "start_position": 0,
                      "end_position": 1,
                      "format_type": "Paragraph",
                      "format_attr": "h1"
                    }
                  ],
                  "message": "Hello",
                  "file_ids": [
                    "M87v-bbmRGKCtl8nGNggvA"
                  ],
                  "reply_main_message_id": "{27ED2949-6457-417C-83EA-72515DAF00BD}",
                  "to_channel": "825c9e31f1064c73b394c5e4557d3447",
                  "to_contact": "jchill@example.com",
                  "interactive_cards": [
                    {
                      "card_json": "{   \"content\": {     \"settings\": {       \"default_sidebar_color\": \"#0E72ED\",       \"is_split_sidebar\": false     }   } }"
                    }
                  ],
                  "scheduled_time": "2020-02-10T21:39:50Z"
                }
            }'
